[colors]
[colors.primary]
background = "#3b322b"
foreground = "#ccb3b3"

[colors.normal]
black   = "#3b322b"
red     = "#bfaca6"
green   = "#cdb398"
yellow  = "#cdb198"
blue    = "#a9a9bc"
magenta = "#b3b0b5"
cyan    = "#afb3b6"
white   = "#ccc2b3"

[colors.bright]
black   = "#817265"
red     = "#c0aba5"
green   = "#cdb398"
yellow  = "#cdb398"
blue    = "#a8a8bd"
magenta = "#b3b0b5"
cyan    = "#aeb3b7"
white   = "#ccb3b3"

[colors.cursor]
text   = "#3b322b"
cursor = "#ccb3b3"
