accent = "#a9a9bc"
cursor = "#ccb3b3"
foreground = "#ccb3b3"
background = "#3b322b"
selection_foreground = "#ccb3b3"
selection_background = "#a9a9bc"

color0 = "#3b322b"
color1 = "#bfaca6"
color2 = "#cdb398"
color3 = "#cdb198"
color4 = "#a9a9bc"
color5 = "#b3b0b5"
color6 = "#afb3b6"
color7 = "#ccc2b3"
color8 = "#817265"
color9 = "#c0aba5"
color10 = "#cdb398"
color11 = "#cdb398"
color12 = "#a8a8bd"
color13 = "#b3b0b5"
color14 = "#aeb3b7"
color15 = "#ccb3b3"
